### ISSUE TITLE
Readme for v2.1.1 has broken link

### ISSUE THREAD

**Issue by kauedg** [VoronDesign/Voron-2#148]
The README.md file in the v2.1.1 tag has a broken link to the Voron 2.1.1 configurator.

`The second official release of the Voron 2.1.1 3d printer. You can find the BOM in the configurator located at the [Voron Design](http://vorondesign.com/voron2.1) website.`

Either the link should me removed or the configurator should be made available.

**Comment by kauedg** [comment]
Is it possible to make the configurator available again or it's removed because the version is considered obsolete?

What about adding the generated BOMs for the default build sizes to the repository?

**Comment by FHeilmann** [comment]
V2.1 has been superseded twice at this point, so in order to keep clutter low and make sure people grab the correct version we chose to remove the parts related to the old printers.

At this point we wouldn't be able to guarantee their correctness either way and the branches are merely preserved for posterity.

-Florian
