### ISSUE TITLE
V2.4 Wrong M2 self tapping screw in BOM and wrong amount

### ISSUE THREAD

**Issue by lazymaniac** [VoronDesign/Voron-2#162]
Hey

In BOM I found M2x10 listed, but in instruction manual says about M2x8. M2x10 are too long for DIN mounts because they go all the way through.

**Comment by lazymaniac** [comment]
Also the amount is incorrect. Instruction requires 16 screws (2 - z endstop, 4 - xy endstops, 2x2 - skr mounts, 6 - rpi) but in BOM - 10

**Comment by avongil** [comment]
The mcmaster screws are too short to attach the microswitch reliably. The head is also way too big for that application if you want to lay them flat and solder the JST direct. I had to source other ones that had a thinner head and longer body for all the end stops.   The din rails where ground flush.

**Comment by avongil** [comment]
The McMaster linked screws are the correct length for installing the microswitch reliably @ 10mm long.  The head is however way too big for that application if you want to bend the terminals flat and solder the JST. I had to source other ones that had a thinner head for the z end stop.    The  screws for the din rails where ground flush.  An 8mm long screw could be used, but that adds to the cost since a additional pack of 6 or 8mm long screws would need to be purchased.  In my opinion a bag of M1.91 x 10mm or  #1 X 3/8" long Philips head screw would be ideal. The builder can buy a 50 or 100 pack bag and cut them to size.  

The Digikey switches have holes that are a tiny bit larger than 2mm, so it would not hurt to keep the McMaster linked screw at 1.91mm. The linked McMaster screw is an M1.91 https://www.mcmaster.com/99397A267/   - these screws I was not a fan of. Note how big the head is - 4mm. 
 
 I propose this mcmaster part number - they are a much better fit for the switches and will work everywhere:   
 
 https://www.mcmaster.com/99461A620/

Pics to follow. 
 

Current screws in the BOM from McMaster (head diameter too large):
![image](https://user-images.githubusercontent.com/6765151/148852089-0fdbd35f-2b88-4a9d-9ac9-815a272f5113.png)

![image](https://user-images.githubusercontent.com/6765151/148852192-6315a809-8cf0-473a-ab52-3da9ba458adc.png)

DigiKey microswitches on the BOM have holes that are 0.081" in diameter - 2.06mm.  

![image](https://user-images.githubusercontent.com/6765151/148852471-677f7620-1f4c-4393-98a6-7e22c5e6f811.png)

**Comment by avongil** [comment]
Confirmed the mcmaster part: https://www.mcmaster.com/99461A620/
Is a way better fit, and also easier to cut if you have to although it looks like the new style din connectors are made for it. Great job Steve!  Gorgeous and well labeled parts.  
![image](https://user-images.githubusercontent.com/6765151/149633597-07a40508-741f-4634-956f-7fec2d7ab310.png)



I did not want to bust off the flap, but this fits way nicer than the official linked mcmaster part in the microswitch.  3.5 fully engaged threads. 
![image](https://user-images.githubusercontent.com/6765151/149633438-2e340fe2-0527-4efc-b85a-6c31458e4823.png)
![image](https://user-images.githubusercontent.com/6765151/149633454-d753c620-8ddb-431a-98f1-74201e686bb1.png)
