### ISSUE TITLE
[V2.4] Current CAD step file ZIP archive corrupted

### ISSUE THREAD

**Issue by craxoor** [VoronDesign/Voron-2#236]
The current ZIP archive which contains the latest CAD step file seems to be corrupted. I cannot unpack the file with various ZIP tools.

https://github.com/VoronDesign/Voron-2/blob/5ebe725ef6435274c22f2442686cdbfd98a2b59c/CAD/VORON2_v2.4_Assembly_Step.zip

**Comment by stvptrsn** [comment]
Hello, can you give more details on your environment?  I've double checked the archive and I can unpack it and import the model without issue on a windows based computer.

**Comment by nielsvz** [comment]
I just tested this on macOS 11.2.3 with a few archiving tools:
* Archive Utility (bundled with macOS) - Fail, see screenshot below
* BetterZip - Pass
* Keka - Pass
* `unzip` (in Terminal) - Pass

<img width="490" alt="Screenshot 2021-05-18 at 09 40 58" src="https://user-images.githubusercontent.com/81711/118611789-7e43b300-b7bd-11eb-94d4-92da39cfd539.png">

Update:
Looks like the CRC checksum for the step file in the .zip doesn't match:
```
zip -F VORON2_v2.4_Assembly_Step.zip --out VORON2_v2.4_Assembly_Step.fixed.zip                                                                                                         Tue May 18 09:46:49 2021
Fix archive (-F) - assume mostly intact archive
Zip entry offsets do not need adjusting
 copying: VORON2 v2.4 Assembly.step
	zip warning: Local Entry CRC does not match CD: VORON2 v2.4 Assembly.step
```

I tested the same command with the .zip from a [different commit](https://github.com/VoronDesign/Voron-2/blob/ee9e51a65d14d5b71c995a5fa477df02e350ba51/CAD/VORON2_v2.4_Assembly_Step.zip), that passes without an error:
```
zip -F VORON2_v2.4_Assembly_Step-2.zip --out VORON2_v2.4_Assembly_Step-2.fixed.zip                                                                                                         Tue May 18 09:47:00 2021
Fix archive (-F) - assume mostly intact archive
Zip entry offsets do not need adjusting
 copying: VORON2 v2.4 Assembly.step
```

**Comment by craxoor** [comment]
> Hello, can you give more details on your environment? I've double checked the archive and I can unpack it and import the model without issue on a windows based computer.

Yes, as already mentioned by @nielsvz, this happens with the integrated zip tool of macOS. I have also tested it with a third party zip tool named "Entropy". With that I get the same error while unpacking the archive.

**Comment by stvptrsn** [comment]
I'll try another utility to create the archive and upload it.

**Comment by CyberCastle** [comment]
Hi, the mentioned error with this file https://github.com/VoronDesign/Voron-2/blob/Voron2.4/CAD/VORON2_v2.4_Assembly_Step.zip, remains.

**Comment by ejplaysintraffic** [comment]
The current step file remains corrupted.
While the archive may be fine, the file is not.
I am a designer in our engineering department and running SolidWorks 2020 and the file fails to open and when viewed in notepad, has a large amount of text at the beginning of the file that does not match how other files are formatted when compared to other examples we have on file.

**Comment by ejplaysintraffic** [comment]
Step files are intended to open in any program. This one does not. I will
link to a tech article that explains how to use the file in SolidWorks
despite the fusion file creation. Not everyone uses Fusion 3d. It would be
cool if there was a note for SolidWorks users added, explaining that Fusion
creates non-standard files and how you can work around it.
Closing a bug report without testing or explanation is a bit heavy handed
and not how open source is usually documented.
Merely being able to open the file with the same software that created it,
in no way verifies that the file works cross platform.

The idea is to share with as many people as possible, rather than
discriminate in favor of one program over another.

Here is a link, explaining why all the extra text in the file breaks the
file for SolidWorks, and more importantly, how to fix it.
https://www.javelin-tech.com/blog/2018/11/encountered-invalid-record-index-solidworks/

Thank you,

EJ

**Comment by FHeilmann** [comment]
The issue was closed automatically by GitHub because a pull request that was linked to this issue was merged. So no need to call anyone heavy handed or in conflict with open source practices here. Accusing us of discriminating against a certain group of users is also pretty uncalled for. Many of our designers use SOLIDWORKS themselves. So if there's still a need to fix up the files further I'll welcome a solution via a pull request from you.

-Florian

**Comment by ejplaysintraffic** [comment]
No worries man. I just replied to what I saw from my end.

It just showed closed with no explanation.

Github is new territory for me. I do SolidWorks design for a living, and
deal with customer files that may or may not work.

If you could tie the link to fix the file to the issue, or even put it in
the download instructions for the files, that would be fantastic.

I don't know what the pull request is to submit one.

Thanks again,

EJ

**Comment by FHeilmann** [comment]
@ejplaysintraffic please check the zip files from #265 and let me know whether that fixes your issues.

-Florian

**Comment by ejplaysintraffic** [comment]
I got the file to download and repaired the .step file previously, however, the file currently available for download is still a no-go.

The zip archive now fails to unpack properly.

It might be easier just to sticky the work around to the main files? 

The image below is of the current file when attempting to unzip it with 7zip.
![image](https://user-images.githubusercontent.com/89992852/133319377-46308911-b3c2-4df0-8142-cdd287f3721e.png)



**** edit, I forgot to say thank you for your efforts Florian. It is much appreciated

**Comment by FHeilmann** [comment]
just to be absolutely sure, this is the file you downloaded?

https://github.com/VoronDesign/Voron-2/blob/f8f5a8f4f0ad763af43dd2ddcf5b74afd33a6182/CAD/VORON2_v2.4_Assembly.step.zip

Thanks for your help!

edit:

Looking at your screenshot, you seem to have grabbed the wrong file, the file from the PR is named 
`VORON2_v2.4_Assembly.step.zip`
the one you opened in your screenshot is
`VORON2_v2.4_Assembly_Step.zip`

**Comment by ejplaysintraffic** [comment]
I tried all the files, including the one you linked and none work with SolidWorks... The versions that our company is kind enough to pay for, not some cracked version with who knows what in it... 

To be honest, I am kind of at my wit's end. Step files were intended to be a universal format but Fusion often creates non usable files. 
I modified the file by doing a text replacement to make the file open, and other people can do that, if we leave them a link as it is not always intuitive to go looking for that issue. 
I got what I needed from the file, but was trying to ensure that other people don't turn away from the Voron in frustration. 
Having the 3D files to modify rather than trying to take measurements from a proprietary printer such as Creality offerings is nice.

**Comment by FHeilmann** [comment]
I'm unfortunately at my wits end as well. We've gone through significant lengths this time and talked with other Solidworks 2020/2021 users from our design team. They were all able to unzip and open the file without issue. They even zipped, uploaded, downloaded and unzipped the file again to make sure it doesn't get damaged in the "github-process".

So at this time I unfortunately have to conclude that the problem is more likely on your end than ours. Which version of Solidworks are you using?

We're going to, once again, merge this new updated version, maybe you can try again once that makes it into the main branch, but at this point there's nothing else we can do about it from our side.

-Florian
