### ISSUE TITLE
[V2.4] SKR 1.4 AB motor pinout different in config vs guide

### ISSUE THREAD

**Issue by cbc02009** [VoronDesign/Voron-2#237]
The motor connections in the guide for AB motors are opposite what they are in the config:

wiring guide (pg 2):
![image](https://user-images.githubusercontent.com/39525900/118371397-7e07a580-b57a-11eb-8acf-672b3a67b362.png)

config:
```
[stepper_x]
##	Connected to X on mcu_xye (B Motor)
...
[stepper_y]
##	Connected to Y on mcu_xye (A Motor)
...
```

Someone pointed this out on discord so I figured I'd create an issue.

**Comment by insurgus** [comment]
Some discussion has to be had internally to decide how we are going to standardize this. We used to use A/B and then added X/Y and it has caused some confusion in the community. That coupled with the fact that the configs call for X/Y/Z for the MCU is certainly something we should address.

**Comment by stephenlawrence** [comment]
I prefer xyz vs. A/B myself.

**Comment by NameOfTheDragon** [comment]
> I prefer xyz vs. A/B myself.

Z makes perfect sense but X/Y does not make sense in the context of a CoreXY mechanism, since both motors cause movement in both X and Y. Only by moving both motors is it possible to move in just X or just Y. So which one do you call the X motor and which one the Y motor? It has to be "neither". A/B doesn't really make much sense either because that still doesn't make it obvious which motor is being referred to unless you look it up on a diagram (I would guess this is how errors crept into the docs). In my view, it makes more sense to call them "Left" and "right", because one of them is on the left and the other is on the right. That's still a bit ambiguous because it depends which direction you are looking from, so I would say it is even more clear to call them "Back left" and "Back right" or "BL" and "BR". I think thats as good as it gets in terms of disambiguation and having a name that is "intuitively obvious".

**Comment by stephenlawrence** [comment]
Ok, I changed my preference now to BL and BR. :)

**Comment by cbc02009** [comment]
I agree back left and back right (BL and BR) makes the most sense.

**Comment by mathiasm74** [comment]
I've also noticed this issue. I connected the A motor (BR) to MOTOR0 and B motor (BL) to the MOTOR1 on my Octopus, and the toolhead homed away from the x endstop. The [only solution](https://docs.vorondesign.com/build/startup/#v2-1) to this is to swap the wires. This seems wrong, going by what the documentation says. 

But I'm confused about the source of this problem. I would assume the Voron documentation is correct, but this yields the wrong result. I've noticed that the motors in the illustration appears to point in the wrong direction compared to how they are on a 2.4. Is it possible that they have been reoriented compared to an earlier version, and that the A and B has effectively swapped places without anyone taking notice?
 
![image](https://user-images.githubusercontent.com/917776/154570828-0ada1150-90a3-46e2-b72f-f9b7427a2781.png)
