### ISSUE TITLE
A report of the abusive languages on discord 

### ISSUE THREAD

**Issue by ghost** [VoronDesign/Voron-2#344]
This comment was marked as disruptive content and therefore edited. The original comment is still available with GitHubs versioning

**Comment by flub9** [comment]
For context: I get email notifications for all V2 issues/updates so I can keep in touch with what’s going on.

Speaking fully professionally, this issue has some issues.
1) Not the right place, this is the repo for the V2 design, not if you feel insulted by discord. This is incredibly off topic for the repo.
2) I’m assuming this was written hastily or translated, because it is quite difficult to actually understand what the problem is
3) Based on your description, it seems you already resolved any issues by contacting Discord support
4) As a general git-hub rule, keep issues wherever they originated, so in this case, if your issue is in discord, keep it there.


Requesting to close.
-Flub

**Comment by ghost** [comment]
No it has not been closed until discord has finished the investigation this issue also show how unprofessional your design team really are

**Comment by VinnyCordeiro** [comment]
> No it has not been closed until discord has finished the investigation this issue also show how unprofessional your design team really are

Strange, because no one on the dev team is paid for what they do. This is an entirely voluntary project, so you can't really talk about people being unprofessional.

Other than that, if your problem is on Discord, solve it on Discord. Polluting Github with complaints, even if you are right, won't help you.

**Comment by stvptrsn** [comment]
This won't be productive.  This is not the correct channel for this.

**Comment by ghost** [comment]
No this is to show other uses how you really are and one of the abusive member stated he was a on the voron design team
