### ISSUE TITLE
[IDEA] Support for nova hotend

### ISSUE THREAD

**Issue by Dario-Ciceri** [VoronDesign/Voron-2#99]
Hi, is it possibile to have a support for 3D passion's nova hotend?

https://3dpassion.com/nova

**Comment by FHeilmann** [comment]
While this hotend, due to it not being used by anyone in our community as far as I'm aware, probably won't make it into this official repo, we have a large modding community over at https://github.com/VoronDesign/VoronUsers where mods, such as a nova hotend mount can be submitted. 

There isn't one right now, but I encourage you to use this as an excuse to start getting familiar with CAD software yourself ;)

Bests,

Florian
